### ISSUE TITLE
retry with backoff

### ISSUE THREAD

**Issue by fommil** [Astrac/consierge#14]
I left this running all day and seen a bunch of exceptions in the logs with timeouts. I also got somebody to post a ticket to see if it worked, it didn't :-( I'm guessing here but if the timeout happens in the pipeline of checking a ticket, does that mean the ticket is ignored forever?

**Comment by Astrac** [comment]
I wonder if we were rate-limited by github, at the moment we poll every 10 seconds, probably too often! Can you provide some of those exception logs? 

About the old tickets, if I remember correctly at the moment we don't limit the issues to the new ones (the `since` parameter is disabled) so starting the bot should comment on all the issues that meet its criteria (i.e. the author isn't already a contributor and the issues hasn't been commented on by the bot's user yet).

**Comment by fommil** [comment]
I'll c&p a log next time it happens, it got wiped out on a restart

**Comment by ghost** [comment]
I was able to reproduce the problem. 
GitHub JSON returns smth like:

```
{"message":"API rate limit exceeded for rumoku.","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
```
